### GET request to example server
GET http://localhost:8085/

###

GET http://localhost:8085/content/sample.html

###

GET http://localhost:8085/test

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts?type=real
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts?type=category
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts?type=real&type=category
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts?type=real,category
Accept: application/json
# expect failure

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts/ff0d2b4e-064b-40b6-86a3-bb1f3e4a7025
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/accounts/ff0d2b4e-064b-40b6-86a3-bb1f3e4a7025/transactions
Accept: application/json

###

GET http://localhost:8085/budgets/bffc0cec-a00e-41dc-9325-09e768a08e43/transactions/57000ace-20b1-4f2d-aea1-c963f0e1f714
Accept: application/json

###

